### ISSUE TITLE
Use explicitly declaration in function variables in MarketPlace

### ISSUE THREAD

**Issue by bluesign** [portto/bloctobay-contracts#1]
Context: 

https://github.com/portto/bloctobay-contracts/blob/f0f5000857af4d07e5aadc336e824d6bd161b40f/contracts/Marketplace.cdc#L100

`Capability<&{NFTStorefront.StorefrontPublic}` which is equal to `Capability<&AnyResource{NFTStorefront.StorefrontPublic}` is not secure. 

Unfortunately, NFTStorefront lacks required checks in the public interface. This can cause troubles when contract deployments are opened to public. Better to use explicit declaration. 

From first look, it looks like I can remove someone else's listing at least ( maybe also avoid royalties ) , though I haven't dig deeper.

**Comment by scottphc** [comment]
The design is that anyone can remove the listing item from Marketplace contract if the listing item has been removed or purchased from NFTStorefront.

**Comment by bluesign** [comment]
hey @scottphc, thanks for the response. 

I meant I can remove when it is not removed or purchased. 

`Capability<&AnyResource{NFTStorefront.StorefrontPublic}` is not secure, should be `Capability<&NFTStorefront.Storefront{NFTStorefront.StorefrontPublic}`

Otherwise I can make a fake listing by:
-  deploying a contract and creating a resource that implementing `{NFTStorefront.StorefrontPublic}`
- Call `pub fun addListing(id: UInt64, storefrontPublicCapability: Capability<&{NFTStorefront.StorefrontPublic}>) `
- ListingDetails I can create with any NFT ID  ( https://github.com/onflow/nft-storefront/blob/61c8af92adca73d679ff39c9dc190c37bd05eed1/contracts/NFTStorefront.cdc#L143 )
- So It will see as duplicate but difference address 
- So it will update with fake and remove the old listing

In general you always should use original `&NFTStorefront.Storefront{NFTStorefront.StorefrontPublic}` unless you want people to use other resources implementing that interface, but unfortunately NFTStorefront interface is not secure enough, so best option to use explicit declaration 

Also with same logic I can avoid cuts:

- I can create a legit storefront with 0 royalty cuts ( only 1 cut to myself) 
- then I can make a listing with my fake resource implementing interface returning the listingID as same as my legit one
- when you call `getDetails`, I show you another listing with royalty cuts. 


But other than this, this is the best usage of storefront contract.

**Comment by scottphc** [comment]
hi @bluesign, thanks for the detailed explanation.

Yes, you're right. I agree with you that better to use explicit declaration. For now we're tracking listings by NFTStorefront events, not by Marketplace contract. So listing items are safe on BloctoBay. But if someone is tracking listings by Marketplace contract, it may be affected. I'll make a PR for fixing this issue.
